-- phpMyAdmin SQL Dump
-- version 5.1.3
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1
-- Üretim Zamanı: 04 Oca 2025, 14:27:29
-- Sunucu sürümü: 10.4.24-MariaDB
-- PHP Sürümü: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `php-commerce`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `musteri`
--

CREATE TABLE `musteri` (
  `id` int(11) NOT NULL,
  `ad` varchar(20) NOT NULL,
  `soyad` varchar(20) NOT NULL,
  `email` varchar(30) NOT NULL,
  `sifre` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Tablo döküm verisi `musteri`
--

INSERT INTO `musteri` (`id`, `ad`, `soyad`, `email`, `sifre`) VALUES
(1, 'admin', '', 'admin@admin.com', '21092003anil'),
(2, 'Anıl', 'Uzuner', 'worzeg.tr@outlook.com', '21092003anil');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `urunler`
--

CREATE TABLE `urunler` (
  `id` int(11) NOT NULL,
  `kategori` varchar(15) NOT NULL,
  `marka` varchar(15) NOT NULL,
  `model` varchar(15) NOT NULL,
  `baslik` text NOT NULL,
  `fiyat` int(11) NOT NULL,
  `stok` int(11) NOT NULL,
  `gorsel` text NOT NULL,
  `ozellikler` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Tablo döküm verisi `urunler`
--

INSERT INTO `urunler` (`id`, `kategori`, `marka`, `model`, `baslik`, `fiyat`, `stok`, `gorsel`, `ozellikler`) VALUES
(1, 'İşlemci', 'Amd', 'Ryzen 5', 'AMD Ryzen 5 5600 3.5GHz 32MB Önbellek 6 Çekirdek AM4 7nm İşlemci', 4200, 10, 'images/urunler/cpu-amd-r5-5600.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>AM4</td> </tr>\r\n  <tr> <td>İşlemci Serisi:</td> <td>AMD Ryzen 5</td> </tr>\r\n  <tr> <td>Frekans Hızı:</td> <td>3.5 GHz</td> </tr>\r\n  <tr> <td>Max Frekans Hızı:</td> <td>4.4 GHz</td> </tr>\r\n  <tr> <td>Çekirdek Sayısı:</td> <td>6 Çekirdek</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>İş Parçacığı Sayısı:</td> <td>12</td> </tr>\r\n  <tr> <td>L3 Önbellek:</td> <td>32MB</td> </tr>\r\n  <tr> <td>Üretim Teknolojisi:</td> <td>7nm</td> </tr>\r\n  <tr> <td>Tüketim Değeri:</td> <td>65W</td> </tr>\r\n  <tr> <td>Uyumlu Soketler:</td> <td>AM4</td> </tr>\r\n</table>\r\n            '),
(2, 'İşlemci', 'Amd', 'Ryzen 5', 'AMD Ryzen 5 5500 3.6GHz 16MB Önbellek 6 Çekirdek AM4 7nm İşlemci', 3100, 8, 'images/urunler/cpu-amd-r5-5600.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>AM4</td> </tr>\r\n  <tr> <td>İşlemci Serisi:</td> <td>AMD Ryzen 5</td> </tr>\r\n  <tr> <td>Frekans Hızı:</td> <td>3.6 GHz</td> </tr>\r\n  <tr> <td>Max Frekans Hızı:</td> <td>4.2 GHz</td> </tr>\r\n  <tr> <td>Çekirdek Sayısı:</td> <td>6 Çekirdek</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>İş Parçacığı Sayısı:</td> <td>12</td> </tr>\r\n  <tr> <td>L3 Önbellek:</td> <td>16MB</td> </tr>\r\n  <tr> <td>Üretim Teknolojisi:</td> <td>7nm</td> </tr>\r\n  <tr> <td>Tüketim Değeri:</td> <td>65W</td> </tr>\r\n  <tr> <td>Uyumlu Soketler:</td> <td>AM4</td> </tr>\r\n</table>\r\n            '),
(3, 'İşlemci', 'Amd', 'Ryzen 3', 'AMD Ryzen 3 1200 3.1GHz 8MB Önbellek 4 Çekirdek AM4 14nm Tray İşlemci', 1600, 10, 'images/urunler/cpu-amd-r3-1200.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>AM4 </td> </tr>\r\n  <tr> <td>İşlemci Serisi:</td> <td>AMD Ryzen 3</td> </tr>\r\n  <tr> <td>Frekans Hızı:</td> <td>3.1GHz</td> </tr>\r\n  <tr> <td>Max Frekans Hızı:</td> <td>3.4 GHz</td> </tr>\r\n  <tr> <td>Çekirdek Sayısı:</td> <td>4 Çekirdek</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>İş Parçacığı Sayısı:</td> <td>4</td> </tr>\r\n  <tr> <td>L3 Önbellek:</td> <td>8MB</td> </tr>\r\n  <tr> <td>Üretim Teknolojisi:</td> <td>14nm</td> </tr>\r\n  <tr> <td>Tüketim Değeri:</td> <td>65W</td> </tr>\r\n  <tr> <td>Uyumlu Soketler:</td> <td>AM4</td> </tr>\r\n</table>\r\n            '),
(4, 'İşlemci', 'Amd', 'Ryzen 3', 'AMD Ryzen 3 4100 3.8GHz 4MB Önbellek 4 Çekirdek AM4 7nm MPK İşlemci', 1800, 10, 'images/urunler/cpu-amd-r3-1200.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>AM4</td> </tr>\r\n  <tr> <td>İşlemci Serisi:</td> <td>AMD Ryzen 3</td> </tr>\r\n  <tr> <td>Frekans Hızı:</td> <td>3.8 GHz</td> </tr>\r\n  <tr> <td>Max Frekans Hızı:</td> <td>4.0 GHz</td> </tr>\r\n  <tr> <td>Çekirdek Sayısı:</td> <td>4 Çekirdek</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>İş Parçacığı Sayısı:</td> <td>8</td> </tr>\r\n  <tr> <td>L3 Önbellek:</td> <td>4MB</td> </tr>\r\n  <tr> <td>Üretim Teknolojisi:</td> <td>7nm</td> </tr>\r\n  <tr> <td>Tüketim Değeri:</td> <td>65W</td> </tr>\r\n  <tr> <td>Uyumlu Soketler:</td> <td>AM4</td> </tr>\r\n</table>\r\n            '),
(5, 'İşlemci', 'Amd', 'Ryzen 7', 'AMD RYZEN 7 5700G 3.8GHz 16MB Önbellek 8 Çekirdek AM4 7nm İşlemci', 7000, 10, 'images/urunler/cpu-amd-r7-5700.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>AM4 </td> </tr>\r\n  <tr> <td>İşlemci Serisi:</td> <td>AMD Ryzen 7</td> </tr>\r\n  <tr> <td>Frekans Hızı:</td> <td>3.8 GHz</td> </tr>\r\n  <tr> <td>Max Frekans Hızı:</td> <td>4.6 GHz</td> </tr>\r\n  <tr> <td>Çekirdek Sayısı:</td> <td>8 Çekirdek</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>İş Parçacığı Sayısı:</td> <td>16</td> </tr>\r\n  <tr> <td>L3 Önbellek:</td> <td>16MB</td> </tr>\r\n  <tr> <td>Üretim Teknolojisi:</td> <td>7nm</td> </tr>\r\n  <tr> <td>Tüketim Değeri:</td> <td>65W</td> </tr>\r\n  <tr> <td>Uyumlu Soketler:</td> <td>AM4</td> </tr>\r\n</table>\r\n            '),
(6, 'İşlemci', 'Amd', 'Ryzen 7', 'AMD RYZEN 7 5800X3D 3.4GHz 100MB Önbellek 8 Çekirdek AM4 7nm İşlemci', 10200, 10, 'images/urunler/cpu-amd-r7-5700.jpg', '  \r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>AM4 </td> </tr>\r\n  <tr> <td>İşlemci Serisi:</td> <td>AMD Ryzen 7</td> </tr>\r\n  <tr> <td>Frekans Hızı:</td> <td>3.4 GHz</td> </tr>\r\n  <tr> <td>Max Frekans Hızı:</td> <td>4.5 GHz</td> </tr>\r\n  <tr> <td>Çekirdek Sayısı:</td> <td>8 Çekirdek</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>İş Parçacığı Sayısı:</td> <td>16</td> </tr>\r\n  <tr> <td>L3 Önbellek:</td> <td>100MB</td> </tr>\r\n  <tr> <td>Üretim Teknolojisi:</td> <td>7nm</td> </tr>\r\n  <tr> <td>Tüketim Değeri:</td> <td>105W</td> </tr>\r\n  <tr> <td>Uyumlu Soketler:</td> <td>AM4</td> </tr>\r\n</table>\r\n                        '),
(7, 'İşlemci', 'Amd', 'Ryzen 9', 'AMD RYZEN 9 5950X 3.4GHz 64MB Önbellek 16 Çekirdek AM4 7nm İşlemci', 15300, 10, 'images/urunler/cpu-amd-r9-5950.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>AM4</td> </tr>\r\n  <tr> <td>İşlemci Serisi:</td> <td>AMD Ryzen 9</td> </tr>\r\n  <tr> <td>Frekans Hızı:</td> <td>3.4 GHz</td> </tr>\r\n  <tr> <td>Max Frekans Hızı:</td> <td>4.9 GHz</td> </tr>\r\n  <tr> <td>Çekirdek Sayısı:</td> <td>16 Çekirdek</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>İş Parçacığı Sayısı:</td> <td>32</td> </tr>\r\n  <tr> <td>L3 Önbellek:</td> <td>64MB</td> </tr>\r\n  <tr> <td>Üretim Teknolojisi:</td> <td>7nm</td> </tr>\r\n  <tr> <td>Tüketim Değeri:</td> <td>105W</td> </tr>\r\n  <tr> <td>Uyumlu Soketler:</td> <td>AM4</td> </tr>\r\n</table>\r\n            '),
(8, 'İşlemci', 'Intel', 'Core i3', 'Intel Core i3 10100F 3.60GHz 6MB Önbellek 4 Çekirdek 1200 14nm İşlemci', 1100, 10, 'images/urunler/cpu-intel-i3-10105.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>1200 </td> </tr>\r\n  <tr> <td>İşlemci Serisi:</td> <td>Intel Core i3</td> </tr>\r\n  <tr> <td>Frekans Hızı:</td> <td>3.6 GHz</td> </tr>\r\n  <tr> <td>Max Frekans Hızı:</td> <td>4.3 GHz</td> </tr>\r\n  <tr> <td>Çekirdek Sayısı:</td> <td>4 Çekirdek</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>İş Parçacığı Sayısı:</td> <td>8</td> </tr>\r\n  <tr> <td>L3 Önbellek:</td> <td>6MB</td> </tr>\r\n  <tr> <td>Üretim Teknolojisi:</td> <td>14nm</td> </tr>\r\n  <tr> <td>Tüketim Değeri:</td> <td>65W</td> </tr>\r\n  <tr> <td>Uyumlu Soketler:</td> <td>1200</td> </tr>\r\n</table>\r\n            '),
(9, 'İşlemci', 'Intel', 'Core i5', 'Intel Core i5 12400F 4.40GHz 18MB Önbellek 6 Çekirdek Soket 1700 10nm İşlemci', 3000, 10, 'images/urunler/cpu-intel-i5-12400.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>1700</td> </tr>\r\n  <tr> <td>İşlemci Serisi:</td> <td>Intel Core i5</td> </tr>\r\n  <tr> <td>Frekans Hızı:</td> <td>2.5 GHz</td> </tr>\r\n  <tr> <td>Max Frekans Hızı:</td> <td>4.4 GHz</td> </tr>\r\n  <tr> <td>Çekirdek Sayısı:</td> <td>6 Çekirdek</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>İş Parçacığı Sayısı:</td> <td>12</td> </tr>\r\n  <tr> <td>L3 Önbellek:</td> <td>18MB</td> </tr>\r\n  <tr> <td>Üretim Teknolojisi:</td> <td>10nm</td> </tr>\r\n  <tr> <td>Tüketim Değeri:</td> <td>65W</td> </tr>\r\n  <tr> <td>Uyumlu Soketler:</td> <td>1700</td> </tr>\r\n</table>\r\n            '),
(10, 'İşlemci', 'Intel', 'Core i7', 'Intel Core i7 11700KF 3.6GHz 16MB Önbellek 8 Çekirdek 1200 14nm İşlemci', 7300, 10, 'images/urunler/cpu-intel-i7-11700.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>1200 </td> </tr>\r\n  <tr> <td>İşlemci Serisi:</td> <td>Intel Core i7</td> </tr>\r\n  <tr> <td>Frekans Hızı:</td> <td>3.6 GHz</td> </tr>\r\n  <tr> <td>Max Frekans Hızı:</td> <td>4.9 GHz</td> </tr>\r\n  <tr> <td>Çekirdek Sayısı:</td> <td>8 Çekirdek</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>İş Parçacığı Sayısı:</td> <td>16</td> </tr>\r\n  <tr> <td>L3 Önbellek:</td> <td>16MB</td> </tr>\r\n  <tr> <td>Üretim Teknolojisi:</td> <td>14nm</td> </tr>\r\n  <tr> <td>Tüketim Değeri:</td> <td>125W</td> </tr>\r\n  <tr> <td>Uyumlu Soketler:</td> <td>1200</td> </tr>\r\n</table>\r\n            '),
(11, 'İşlemci', 'Intel', 'Core i9', 'Intel Core i9 11900KF 3.5GHz 16MB Önbellek 8 Çekirdek 1200 14nm İşlemci', 12000, 10, 'images/urunler/cpu-intel-i9-11900.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>1200 </td> </tr>\r\n  <tr> <td>İşlemci Serisi:</td> <td>Intel Core i9</td> </tr>\r\n  <tr> <td>Frekans Hızı:</td> <td>3.5 GHz</td> </tr>\r\n  <tr> <td>Max Frekans Hızı:</td> <td>5.3 GHz</td> </tr>\r\n  <tr> <td>Çekirdek Sayısı:</td> <td>8 Çekirdek</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>İş Parçacığı Sayısı:</td> <td>16</td> </tr>\r\n  <tr> <td>L3 Önbellek:</td> <td>16MB</td> </tr>\r\n  <tr> <td>Üretim Teknolojisi:</td> <td>14nm</td> </tr>\r\n  <tr> <td>Tüketim Değeri:</td> <td>125W</td> </tr>\r\n  <tr> <td>Uyumlu Soketler:</td> <td>1200</td> </tr>\r\n</table>\r\n            '),
(12, 'İşlemci', 'Intel', 'Core i9', 'Intel Core i9 12900F 3.8GHz 30MB Önbellek 16 Çekirdek 1700 10nm İşlemci', 11200, 10, 'images/urunler/cpu-intel-i9-12900.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>1700</td> </tr>\r\n  <tr> <td>İşlemci Serisi:</td> <td>Intel Core i9</td> </tr>\r\n  <tr> <td>Frekans Hızı:</td> <td>3.8 GHz</td> </tr>\r\n  <tr> <td>Max Frekans Hızı:</td> <td>5.1 GHz</td> </tr>\r\n  <tr> <td>Çekirdek Sayısı:</td> <td>16 Çekirdek</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>İş Parçacığı Sayısı:</td> <td>24</td> </tr>\r\n  <tr> <td>L3 Önbellek:</td> <td>30MB</td> </tr>\r\n  <tr> <td>Üretim Teknolojisi:</td> <td>10nm</td> </tr>\r\n  <tr> <td>Tüketim Değeri:</td> <td>65W</td> </tr>\r\n  <tr> <td>Uyumlu Soketler:</td> <td>1700</td> </tr>\r\n</table>\r\n            '),
(13, 'Anakart', 'Msi', 'Intel', 'MSI PRO B660M-A WIFI 6200MHz(OC) DDR5 Soket 1700 M.2 HDMI DP mATX Anakart', 3800, 10, 'images/urunler/mb-msi-intel-b660.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>1700</td> </tr>\r\n  <tr> <td>Chipset:</td> <td>Intel B660</td> </tr>\r\n  <tr> <td>Ram Slot Sayısı:</td> <td>4</td> </tr>\r\n  <tr> <td>Max Ram Desteği:</td> <td>128GB</td> </tr>\r\n  <tr> <td>Ram Tipi:</td> <td>DDR5</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>6200 MHz</td> </tr>\r\n  <tr> <td>Anakart Boyut:</td> <td>Micro ATX</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x6</td> </tr>\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 6</td> </tr>\r\n  <tr> <td>Ses Çipi:</td> <td>Realtek </td> </tr>\r\n</table>\r\n            '),
(14, 'Anakart', 'Msi', 'Amd', 'MSI MAG X570S TORPEDO MAX 5100MHz(OC) DDR4 Soket AM4 M.2 HDMI ATX Anakart', 4000, 10, 'images/urunler/mb-msi-amd-x570.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>AM4 </td> </tr>\r\n  <tr> <td>Chipset:</td> <td>AMD X570</td> </tr>\r\n  <tr> <td>Ram Slot Sayısı:</td> <td>4</td> </tr>\r\n  <tr> <td>Max Ram Desteği:</td> <td>128GB</td> </tr>\r\n  <tr> <td>Ram Tipi:</td> <td>DDR4</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>5100 MHz</td> </tr>\r\n  <tr> <td>Anakart Boyut:</td> <td>ATX</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x 9</td> </tr>\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 6</td> </tr>\r\n  <tr> <td>Ses Çipi:</td> <td>Realtek</td> </tr>\r\n</table>\r\n            '),
(15, 'Anakart', 'Asus', 'Amd', 'ASUS TUF GAMING X570-PRO WIFI 4400MHz(OC) DDR4 Soket AM4 RGB M.2 PCIe 4.0 HDMI DP WIFI ATX Anakart', 4300, 10, 'images/urunler/mb-asus-amd-x570.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>AM4 </td> </tr>\r\n  <tr> <td>Chipset:</td> <td>AMD X570</td> </tr>\r\n  <tr> <td>Ram Slot Sayısı:</td> <td>4</td> </tr>\r\n  <tr> <td>Max Ram Desteği:</td> <td>128GB</td> </tr>\r\n  <tr> <td>Ram Tipi:</td> <td>DDR4</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>4400 MHz</td> </tr>\r\n  <tr> <td>Anakart Boyut:</td> <td>ATX</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x 11</td> </tr>\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 4</td> </tr>\r\n  <tr> <td>Ses Çipi:</td> <td>Realtek</td> </tr>\r\n</table>\r\n            '),
(16, 'Anakart', 'Asus', 'Amd', 'ASUS PRIME X570-P 4400MHz(OC) DDR4 Soket AM4 M.2 PCIe 4.0 HDMI ATX Anakart', 2300, 10, 'images/urunler/mb-asus-amd-prime.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>AM4 </td> </tr>\r\n  <tr> <td>Chipset:</td> <td>AMD X570</td> </tr>\r\n  <tr> <td>Ram Slot Sayısı:</td> <td>4</td> </tr>\r\n  <tr> <td>Max Ram Desteği:</td> <td>128GB</td> </tr>\r\n  <tr> <td>Ram Tipi:</td> <td>DDR4</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>4400 MHz</td> </tr>\r\n  <tr> <td>Anakart Boyut:</td> <td>ATX</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x 10</td> </tr>\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 5</td> </tr>\r\n  <tr> <td>Ses Çipi:</td> <td>Realtek</td> </tr>\r\n</table>\r\n            '),
(17, 'Anakart', 'Gigabyte', 'Intel', 'GIGABYTE Z690 GAMING X 5333MHz(OC) DDR5 Soket 1700 M.2 HDMI DP ATX Anakart', 5500, 10, 'images/urunler/mb-gigabyte-intel-z690.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>1700</td> </tr>\r\n  <tr> <td>Chipset:</td> <td>Intel Z690</td> </tr>\r\n  <tr> <td>Ram Slot Sayısı:</td> <td>4</td> </tr>\r\n  <tr> <td>Max Ram Desteği:</td> <td>128GB</td> </tr>\r\n  <tr> <td>Ram Tipi:</td> <td>DDR5</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>5333 MHz</td> </tr>\r\n  <tr> <td>Anakart Boyut:</td> <td>ATX</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x 7</td> </tr>\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 8</td> </tr>\r\n  <tr> <td>Ses Çipi:</td> <td>Realtek</td> </tr>\r\n</table>\r\n            '),
(18, 'Anakart', 'Gigabyte', 'Amd', 'GIGABYTE A520M DS3H 4400MHz(OC) DDR4 Soket AM4 M.2 VGA DVI HDMI mATX Anakart', 1600, 8, 'images/urunler/mb-gigabyte-amd-a520.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>AM4 </td> </tr>\r\n  <tr> <td>Chipset:</td> <td>AMD A520</td> </tr>\r\n  <tr> <td>Ram Slot Sayısı:</td> <td>4</td> </tr>\r\n  <tr> <td>Max Ram Desteği:</td> <td>64GB</td> </tr>\r\n  <tr> <td>Ram Tipi:</td> <td>DDR4</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>5100 MHz</td> </tr>\r\n  <tr> <td>Anakart Boyut:</td> <td>Micro ATX</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x 6</td> </tr>\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 4</td> </tr>\r\n  <tr> <td>Ses Çipi:</td> <td>Realtek</td> </tr>\r\n</table>\r\n            '),
(19, 'Anakart', 'Msi', 'Intel', 'MSI MPG Z690 EDGE WIFI DDR4 5200MHz(OC) DDR4 Soket 1700 M.2 HDMI DP ATX Anakart', 7100, 10, 'images/urunler/mb-msi-intel-z690.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>1700</td> </tr>\r\n  <tr> <td>Chipset:</td> <td>Intel Z690</td> </tr>\r\n  <tr> <td>Ram Slot Sayısı:</td> <td>4</td> </tr>\r\n  <tr> <td>Max Ram Desteği:</td> <td>128GB</td> </tr>\r\n  <tr> <td>Ram Tipi:</td> <td>DDR4</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>5200 MHz</td> </tr>\r\n  <tr> <td>Anakart Boyut:</td> <td>ATX</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x 6</td> </tr>\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 4</td> </tr>\r\n  <tr> <td>Ses Çipi:</td> <td>Realtek</td> </tr>\r\n</table>\r\n            '),
(20, 'Anakart', 'Asus', 'Intel', 'ASUS TUF GAMING Z690-PLUS WIFI 6000MHz(OC) DDR5 Soket 1700 M.2 HDMI DP ATX Anakart', 6200, 10, 'images/urunler/mb-asus-intel-tuf-z690.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>1700</td> </tr>\r\n  <tr> <td>Chipset:</td> <td>Intel Z690</td> </tr>\r\n  <tr> <td>Ram Slot Sayısı:</td> <td>4</td> </tr>\r\n  <tr> <td>Max Ram Desteği:</td> <td>128GB</td> </tr>\r\n  <tr> <td>Ram Tipi:</td> <td>DDR5</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>6000 MHz</td> </tr>\r\n  <tr> <td>Anakart Boyut:</td> <td>ATX</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x 7</td> </tr>\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 2</td> </tr>\r\n  <tr> <td>Ses Çipi:</td> <td>Realtek</td> </tr>\r\n</table>\r\n            '),
(21, 'Anakart', 'Gigabyte', 'Intel', 'GIGABYTE Z590 D 5333MHz (OC) DDR4 Soket 1200 M.2 DP ATX Anakart', 3100, 10, 'images/urunler/mb-gigabyte-ıntel-z590.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>İşlemci Soket Tipi:</td> <td>1200 </td> </tr>\r\n  <tr> <td>Chipset:</td> <td>Intel Z590</td> </tr>\r\n  <tr> <td>Ram Slot Sayısı:</td> <td>4</td> </tr>\r\n  <tr> <td>Max Ram Desteği:</td> <td>128GB</td> </tr>\r\n  <tr> <td>Ram Tipi:</td> <td>DDR4</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>5333 MHz</td> </tr>\r\n  <tr> <td>Anakart Boyut:</td> <td>ATX</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x 8</td> </tr>\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 4</td> </tr>\r\n  <tr> <td>Ses Çipi:</td> <td>Realtek</td> </tr>\r\n</table>\r\n            '),
(22, 'Bellek', 'Corsair', 'DDR4', 'CORSAIR 16GB(2x8GB) Vengeance RGB PRO SL Siyah 3600MHz CL18 DDR4 Dual Kit Ram', 2500, 10, 'images/urunler/ram-corsair-ddr4-16gb.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Tipi:</td> <td>DDR4</td> </tr>\r\n  <tr> <td>Ram Kapasitesi:</td> <td>16GB</td> </tr>\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>3600 MHz</td> </tr>\r\n  <tr> <td>Cas Gecikme:</td> <td>18</td> </tr>\r\n<!--  <tr> <td>Ram Tipi:</td> <td>xxx</td> </tr> -->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Voltaj:</td> <td>1.35V</td> </tr>\r\n  <tr> <td>Renk:</td> <td>RGB, Siyah</td> </tr>\r\n  <tr> <td>Kanal Tipi:</td> <td>Dual Kanal</td> </tr>\r\n  <tr> <td>Ram Uyumluluğu:</td> <td>Masaüstü Ram</td> </tr>\r\n<!--  <tr> <td>Ses Çipi:</td> <td>xxx</td> </tr> -->\r\n</table>\r\n            '),
(23, 'Bellek', 'Corsair', 'DDR4', 'CORSAIR 32GB (2x16GB) Vengeance 3000MHz CL18 DDR4 SODIMM Dual Kit Notebook Ram', 3900, 10, 'images/urunler/ram-corsair-ddr4-vengeance.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Tipi:</td> <td>DDR4 </td> </tr>\r\n  <tr> <td>Ram Kapasitesi:</td> <td>32GB</td> </tr>\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>3000 MHz</td> </tr>\r\n  <tr> <td>Cas Gecikme:</td> <td>18</td> </tr>\r\n<!--  <tr> <td>Ram Tipi:</td> <td>xxx</td> </tr> -->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Voltaj:</td> <td>1.2V</td> </tr>\r\n  <tr> <td>Renk:</td> <td>Siyah</td> </tr>\r\n  <tr> <td>Kanal Tipi:</td> <td>Dual Kanal</td> </tr>\r\n  <tr> <td>Ram Uyumluluğu:</td> <td>Notebook Ram</td> </tr>\r\n<!--  <tr> <td>Ses Çipi:</td> <td>xxx</td> </tr> -->\r\n</table>\r\n            '),
(24, 'Depolama', 'Wd', 'HDD', 'WD 3TB Purple 64MB 5400rpm 3.5 SATA 3.0 Güvenlik Harddisk', 1600, 10, 'images/urunler/depolama-wd-hdd-3tb-p.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Disk Boyutu:</td> <td>3.5\"</td> </tr>\r\n  <tr> <td>Kapasite:</td> <td>3TB</td> </tr>\r\n  <tr> <td>Önbellek:</td> <td>64MB</td> </tr>\r\n<!--  <tr> <td>:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Disk Devir Hızı:</td> <td>5400 RPM</td> </tr>\r\n  <tr> <td>Bağlantı Arayüz:</td> <td>SATA 6.0Gb/s</td> </tr>\r\n  <tr> <td></td> <td></td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(25, 'Bellek', 'Corsair', 'DDR5', 'CORSAIR 32GB (2x16GB) Dominator Platinum RGB Siyah 6000MHz CL36 DDR5 Dual Kit Ram', 9700, 10, 'images/urunler/ram-corsair-ddr5-dominator.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Tipi:</td> <td>DDR5</td> </tr>\r\n  <tr> <td>Ram Kapasitesi:</td> <td>32GB</td> </tr>\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>6000 MHz</td> </tr>\r\n  <tr> <td>Cas Gecikme:</td> <td>36</td> </tr>\r\n<!--  <tr> <td>Ram Tipi:</td> <td>xxx</td> </tr> -->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Voltaj:</td> <td>1.25V</td> </tr>\r\n  <tr> <td>Renk:</td> <td>RGB, Siyah</td> </tr>\r\n  <tr> <td>Kanal Tipi:</td> <td>Dual Kanal</td> </tr>\r\n  <tr> <td>Ram Uyumluluğu:</td> <td>Masaüstü Ram</td> </tr>\r\n<!--  <tr> <td>Ses Çipi:</td> <td>xxx</td> </tr> -->\r\n</table>\r\n            '),
(26, 'Bellek', 'Corsair', 'DDR5', 'CORSAIR 64GB (2x32GB) Vengeance 5200MHz CL40 DDR5 Siyah Dual Kit Ram', 12600, 10, 'images/urunler/ram-corsair-ddr5-vengeance.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Tipi:</td> <td>DDR5</td> </tr>\r\n  <tr> <td>Ram Kapasitesi:</td> <td>64GB</td> </tr>\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>5200 MHz</td> </tr>\r\n  <tr> <td>Cas Gecikme:</td> <td>40</td> </tr>\r\n<!--  <tr> <td>Ram Tipi:</td> <td>xxx</td> </tr> -->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Voltaj:</td> <td>1.25V</td> </tr>\r\n  <tr> <td>Renk:</td> <td>Siyah</td> </tr>\r\n  <tr> <td>Kanal Tipi:</td> <td>Dual Kanal</td> </tr>\r\n  <tr> <td>Ram Uyumluluğu:</td> <td>Masaüstü Ram</td> </tr>\r\n<!--  <tr> <td>Ses Çipi:</td> <td>xxx</td> </tr> -->\r\n</table>\r\n            '),
(27, 'Bellek', 'Corsair', 'DDR4', 'CORSAIR 16GB (2x8GB) Vengeance LPX Kırmızı 3200MHz CL16 DDR4 Dual Kit Ram', 1700, 8, 'images/urunler/ram-corsair-ddr4-16gb-vengeance.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ram Tipi:</td> <td>DDR4</td> </tr>\r\n  <tr> <td>Ram Kapasitesi:</td> <td>16GB</td> </tr>\r\n  <tr> <td>Ram Frekans Hızı:</td> <td>3200 MHz</td> </tr>\r\n  <tr> <td>Cas Gecikme:</td> <td>16</td> </tr>\r\n<!--  <tr> <td>Ram Tipi:</td> <td>xxx</td> </tr> -->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Voltaj:</td> <td>1.35V</td> </tr>\r\n  <tr> <td>Renk:</td> <td>Kırmızı</td> </tr>\r\n  <tr> <td>Kanal Tipi:</td> <td>Dual Kanal</td> </tr>\r\n  <tr> <td>Ram Uyumluluğu:</td> <td>Masaüstü Ram</td> </tr>\r\n<!--  <tr> <td>Ses Çipi:</td> <td>xxx</td> </tr> -->\r\n</table>\r\n            '),
(28, 'Ekran Kartı', 'Asus', 'NVIDIA', 'ASUS GeForce GTX 1650 OC Edition 4GB GDDR5 128 Bit Ekran Kartı', 4700, 10, 'images/urunler/gc-asus-nvidia-1650.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>GPU Model:</td> <td>GTX 1650</td> </tr>\r\n  <tr> <td>Max Çekirdek Hızı:</td> <td>1740 MHz</td> </tr>\r\n  <tr> <td>Çekirdek Hızı:</td> <td>1710 MHz</td> </tr>\r\n  <tr> <td>Cuda Sayısı:</td> <td>896</td> </tr>\r\n  <tr> <td>Bellek Tipi:</td> <td>GDDR5</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Bellek Hızı:</td> <td>8002 MHz</td> </tr>\r\n  <tr> <td>Bellek Kapasitesi:</td> <td>4GB</td> </tr>\r\n  <tr> <td>Bellek Arayüzü:</td> <td>128-Bit</td> </tr>\r\n  <tr> <td>HDMI:</td> <td>HDMI 2.0 x 1</td> </tr>\r\n  <tr> <td>Display Port:</td> <td>DP 1.4 x 1</td> </tr>\r\n</table>\r\n            '),
(29, 'Ekran Kartı', 'Asus', 'NVIDIA', 'ASUS GeForce RTX 2060 DUAL 12GB GDDR6 192 Bit Ekran Kartı', 7500, 10, 'images/urunler/gc-asus-nvidia-2060.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>GPU Model:</td> <td>RTX 2060</td> </tr>\r\n  <tr> <td>Max Çekirdek Hızı:</td> <td>1680 MHz</td> </tr>\r\n  <tr> <td>Çekirdek Hızı:</td> <td>1650 MHz</td> </tr>\r\n  <tr> <td>Cuda Sayısı:</td> <td>2176</td> </tr>\r\n  <tr> <td>Bellek Tipi:</td> <td>GDDR6</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Bellek Hızı:</td> <td>14000 MHz</td> </tr>\r\n  <tr> <td>Bellek Kapasitesi:</td> <td>12GB</td> </tr>\r\n  <tr> <td>Bellek Arayüzü:</td> <td>192-Bit</td> </tr>\r\n  <tr> <td>HDMI:</td> <td>HDMI 2.0 x 2</td> </tr>\r\n  <tr> <td>Display Port:</td> <td>DP 1.4a x 1</td> </tr>\r\n</table>\r\n            '),
(30, 'Ekran Kartı', 'Asus', 'NVIDIA', 'ASUS GeForce GT 730 2GB GDDR5 64 Bit Ekran Kartı', 1700, 10, 'images/urunler/gc-asus-nvidia-730.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>GPU Model:</td> <td>GT 730</td> </tr>\r\n  <tr> <td>Max Çekirdek Hızı:</td> <td>925 MHz</td> </tr>\r\n  <tr> <td>Çekirdek Hızı:</td> <td>902 MHz</td> </tr>\r\n  <tr> <td>Cuda Sayısı:</td> <td>384</td> </tr>\r\n  <tr> <td>Bellek Tipi:</td> <td>GDDR5</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Bellek Hızı:</td> <td>5010 MHz</td> </tr>\r\n  <tr> <td>Bellek Kapasitesi:</td> <td>2GB</td> </tr>\r\n  <tr> <td>Bellek Arayüzü:</td> <td>64-Bit</td> </tr>\r\n  <tr> <td>HDMI:</td> <td>HDMI x 1</td> </tr>\r\n  <tr> <td>Display Port:</td> <td>Yok</td> </tr>\r\n</table>\r\n            '),
(31, 'Ekran Kartı', 'Asus', 'Amd', 'ASUS TUF GAMING Radeon RX 6500 XT OC 4GB GDDR6 64 Bit Ekran Kartı', 6000, 10, 'images/urunler/gc-asus-amd-6500.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>GPU Model:</td> <td>RX 6500 XT</td> </tr>\r\n  <tr> <td>Max Çekirdek Hızı:</td> <td>2825 MHz</td> </tr>\r\n  <tr> <td>Çekirdek Hızı:</td> <td>2705 MHz</td> </tr>\r\n  <tr> <td>Stream Sayısı:</td> <td>1024</td> </tr>\r\n  <tr> <td>Bellek Tipi:</td> <td>GDDR6</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Bellek Hızı:</td> <td>18000 MHz</td> </tr>\r\n  <tr> <td>Bellek Kapasitesi:</td> <td>4GB</td> </tr>\r\n  <tr> <td>Bellek Arayüzü:</td> <td>64-Bit</td> </tr>\r\n  <tr> <td>HDMI:</td> <td>HDMI 2.1 x 1</td> </tr>\r\n  <tr> <td>Display Port:</td> <td>DP 1.4a x 1</td> </tr>\r\n</table>\r\n            '),
(32, 'Ekran Kartı', 'Asus', 'Amd', 'ASUS PHOENIX Radeon RX550 4G EVO 4GB GDDR5 128 Bit Ekran Kartı', 3100, 10, 'images/urunler/gc-asus-amd-rx550.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>GPU Model:</td> <td>RX 550</td> </tr>\r\n  <tr> <td>Max Çekirdek Hızı:</td> <td>1186 MHz</td> </tr>\r\n  <tr> <td>Çekirdek Hızı:</td> <td>1183 MHz</td> </tr>\r\n  <tr> <td>Cuda Sayısı:</td> <td>512</td> </tr>\r\n  <tr> <td>Bellek Tipi:</td> <td>GDDR5</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Bellek Hızı:</td> <td>6000 MHz</td> </tr>\r\n  <tr> <td>Bellek Kapasitesi:</td> <td>4GB</td> </tr>\r\n  <tr> <td>Bellek Arayüzü:</td> <td>128-Bit</td> </tr>\r\n  <tr> <td>HDMI:</td> <td>HDMI 2.0 x 1</td> </tr>\r\n  <tr> <td>Display Port:</td> <td>DP 1.4 x 1</td> </tr>\r\n</table>\r\n            '),
(33, 'Ekran Kartı', 'Gigabyte', 'NVIDIA', 'GIGABYTE GeForce RTX 3050 EAGLE GDDR6 8GB 128 Bit Ekran Kartı', 6500, 8, 'images/urunler/gc-gigabyte-nvdia-3050.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>GPU Model:</td> <td> RTX 3050</td> </tr>\r\n  <tr> <td>Max Çekirdek Hızı:</td> <td>1770 MHz</td> </tr>\r\n  <tr> <td>Çekirdek Hızı:</td> <td>1777 MHz</td> </tr>\r\n  <tr> <td>Cuda Sayısı:</td> <td>2560</td> </tr>\r\n  <tr> <td>Bellek Tipi:</td> <td>GDDR6</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Bellek Hızı:</td> <td>14000 MHz</td> </tr>\r\n  <tr> <td>Bellek Kapasitesi:</td> <td>8GB</td> </tr>\r\n  <tr> <td>Bellek Arayüzü:</td> <td>128-Bit</td> </tr>\r\n  <tr> <td>HDMI:</td> <td>HDMI 2.1 x 2</td> </tr>\r\n  <tr> <td>Display Port:</td> <td>DP 1.4a x 2</td> </tr>\r\n</table>\r\n            '),
(34, 'Ekran Kartı', 'Gigabyte', 'NVIDIA', 'GIGABYTE GeForce GTX 1660 OC 6GB GDDR5 192 Bit Ekran Kartı', 7900, 9, 'images/urunler/gc-gigabyte-nvidia-1660.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>GPU Model:</td> <td>GTX 1660</td> </tr>\r\n  <tr> <td>Max Çekirdek Hızı:</td> <td>1830 MHz</td> </tr>\r\n  <tr> <td>Çekirdek Hızı:</td> <td>1830 MHz</td> </tr>\r\n  <tr> <td>Cuda Sayısı:</td> <td>1408</td> </tr>\r\n  <tr> <td>Bellek Tipi:</td> <td>GDDR5</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Bellek Hızı:</td> <td>8000 MHz</td> </tr>\r\n  <tr> <td>Bellek Kapasitesi:</td> <td>6GB</td> </tr>\r\n  <tr> <td>Bellek Arayüzü:</td> <td>192-Bit</td> </tr>\r\n  <tr> <td>HDMI:</td> <td>HDMI x 1</td> </tr>\r\n  <tr> <td>Display Port:</td> <td>DP x 3</td> </tr>\r\n</table>\r\n            '),
(35, 'Ekran Kartı', 'Gigabyte', 'Amd', 'GIGABYTE Radeon RX 6400 D6 Low Profile 4GB GDDR6 64 Bit Ekran Kartı', 4400, 10, 'images/urunler/gc-gigabyte-amd-6400.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>GPU Model:</td> <td>RX 6400</td> </tr>\r\n  <tr> <td>Max Çekirdek Hızı:</td> <td>2321 MHz</td> </tr>\r\n  <tr> <td>Çekirdek Hızı:</td> <td>2015 MHz</td> </tr>\r\n  <tr> <td>Stream Sayısı:</td> <td>768</td> </tr>\r\n  <tr> <td>Bellek Tipi:</td> <td>GDDR6</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Bellek Hızı:</td> <td>16000 MHz</td> </tr>\r\n  <tr> <td>Bellek Kapasitesi:</td> <td>4GB</td> </tr>\r\n  <tr> <td>Bellek Arayüzü:</td> <td>64-Bit</td> </tr>\r\n  <tr> <td>HDMI:</td> <td>HDMI 2.1 x 1</td> </tr>\r\n  <tr> <td>Display Port:</td> <td>DP 1.4 x 1</td> </tr>\r\n</table>\r\n            '),
(36, 'Ekran Kartı', 'Msi', 'NVIDIA', 'MSI GeForce GT 1030 2GHD4 LP OC 2GB DDR4 64 Bit Ekran Kartı', 2100, 10, 'images/urunler/gc-msi-nvidia-1030.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>GPU Model:</td> <td>GT 1030</td> </tr>\r\n  <tr> <td>Max Çekirdek Hızı:</td> <td>1430 MHz</td> </tr>\r\n  <tr> <td>Çekirdek Hızı:</td> <td>1189 MHz</td> </tr>\r\n  <tr> <td>Cuda Sayısı:</td> <td>384</td> </tr>\r\n  <tr> <td>Bellek Tipi:</td> <td>GDDR4</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Bellek Hızı:</td> <td>2100 MHz</td> </tr>\r\n  <tr> <td>Bellek Kapasitesi:</td> <td>2GB</td> </tr>\r\n  <tr> <td>Bellek Arayüzü:</td> <td>64-Bit</td> </tr>\r\n  <tr> <td>HDMI:</td> <td>HDMI x 1</td> </tr>\r\n  <tr> <td>Display Port:</td> <td>DP 1.4a x 1</td> </tr>\r\n</table>\r\n            '),
(37, 'Ekran Kartı', 'Msi', 'Amd', 'MSI Radeon RX 6600 MECH 2X 8GB GDDR6 128 Bit Ekran Kartı', 7600, 9, 'images/urunler/gc-msi-amd-6600.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>GPU Model:</td> <td>RX 6600</td> </tr>\r\n  <tr> <td>Max Çekirdek Hızı:</td> <td>2491 MHz</td> </tr>\r\n  <tr> <td>Çekirdek Hızı:</td> <td>2491 MHz</td> </tr>\r\n  <tr> <td>Stream Sayısı:</td> <td>1792</td> </tr>\r\n  <tr> <td>Bellek Tipi:</td> <td>GDDR6</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Bellek Hızı:</td> <td>14000 MHz</td> </tr>\r\n  <tr> <td>Bellek Kapasitesi:</td> <td>8GB</td> </tr>\r\n  <tr> <td>Bellek Arayüzü:</td> <td>128-Bit</td> </tr>\r\n  <tr> <td>HDMI:</td> <td>HDMI 2.1 x 1</td> </tr>\r\n  <tr> <td>Display Port:</td> <td>DP 1.4 x 3</td> </tr>\r\n</table>\r\n            '),
(38, 'Kasa', 'Asus', 'PSU Yok', 'ASUS TUF GAMING GT301 RGB Tempered Glass USB 3.2 Mid Tower Kasa', 1300, 10, 'images/urunler/kasa-asus-gt301.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kasa Tipi:</td> <td>ATX Mid Tower</td> </tr>\r\n  <tr> <td>PSU:</td> <td>Yok</td> </tr>\r\n  <tr> <td>PSU Konumu:</td> <td>Aşağıda</td> </tr>\r\n  <tr> <td>Internal 3.5\":</td> <td>2</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>4</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 1</td> </tr>\r\n  <tr> <td>USB 3.0:</td> <td>USB 3.0 x 4</td> </tr>\r\n  <tr> <td>USB 3.1:</td> <td>USB 3.1 x 2</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x 2</td> </tr>\r\n  <tr> <td>Fan:</td> <td>120mm x 4</td> </tr>\r\n</table>\r\n            '),
(39, 'Kasa', 'Asus', 'PSU Yok', 'ASUS TUF GAMING GT501 White Edition RGB Tempered Glass USB 3.1 Mid Tower Kasa', 4500, 10, 'images/urunler/kasa-asus-gt501.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kasa Tipi:</td> <td>ATX Mid Tower</td> </tr>\r\n  <tr> <td>PSU:</td> <td>Yok</td> </tr>\r\n  <tr> <td>PSU Konumu:</td> <td>Aşağıda</td> </tr>\r\n  <tr> <td>Internal 3.5\":</td> <td>2</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>2</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 2</td> </tr>\r\n  <tr> <td>USB 3.0:</td> <td>USB 3.0 x 2</td> </tr>\r\n  <tr> <td>USB 3.1:</td> <td>Yok</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>Yok</td> </tr>\r\n  <tr> <td>Fan:</td> <td>120mm x 3, 140mm x 1</td> </tr>\r\n</table>\r\n            '),
(40, 'Kasa', 'Corsair', 'PSU Var', 'CORSAIR Carbide Serisi SPEC-05 650W 80+ Bronze USB 3.0 Siyah Mid Tower Kasa', 2200, 10, 'images/urunler/kasa-corsair-spec05.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kasa Tipi:</td> <td>ATX Mid Tower</td> </tr>\r\n  <tr> <td>PSU:</td> <td>650W</td> </tr>\r\n  <tr> <td>PSU Konumu:</td> <td>Aşağıda</td> </tr>\r\n  <tr> <td>Internal 3.5\":</td> <td>2</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>3</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 1</td> </tr>\r\n  <tr> <td>USB 3.0:</td> <td>USB 3.0 x 1</td> </tr>\r\n  <tr> <td>USB 3.1:</td> <td>Yok</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>Yok</td> </tr>\r\n  <tr> <td>Fan:</td> <td>120mm x 2</td> </tr>\r\n</table>\r\n            '),
(41, 'Kasa', 'Corsair', 'PSU Var', 'CORSAIR Carbide SPEC-DELTA RGB 550W 80+ Bronze Tempered Glass Mid Tower Kasa', 2000, 8, 'images/urunler/kasa-corsair-specdelta.jpg', '<table class=\"urun-table\">\r\n  <tr> <td>Kasa Tipi:</td> <td>ATX Mid Tower</td> </tr>\r\n  <tr> <td>PSU:</td> <td>550W</td> </tr>\r\n  <tr> <td>PSU Konumu:</td> <td>Aşağıda</td> </tr>\r\n  <tr> <td>Internal 3.5\":</td> <td>2</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>2</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 1</td> </tr>\r\n  <tr> <td>USB 3.0:</td> <td>USB 3.0 x 1</td> </tr>\r\n  <tr> <td>USB 3.1:</td> <td>USB 3.1 x 1</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>Yok</td> </tr>\r\n  <tr> <td>Fan:</td> <td>120mm x 4</td> </tr>\r\n</table>\r\n            '),
(42, 'Kasa', 'Gigabyte', 'PSU Yok', 'GIGABYTE AORUS C700 GLASS USB 3.2 Type-C RGB Fusion 2.0 E-ATX Siyah Full Tower Kasa', 9900, 10, 'images/urunler/kasa-gigabyte-c700.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kasa Tipi:</td> <td>E-ATX Full Tower</td> </tr>\r\n  <tr> <td>PSU:</td> <td>Yok</td> </tr>\r\n  <tr> <td>PSU Konumu:</td> <td>Aşağıda</td> </tr>\r\n  <tr> <td>Internal 3.5\":</td> <td>4</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>6</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>USB 2.0:</td> <td>Yok</td> </tr>\r\n  <tr> <td>USB 3.0:</td> <td>USB 3.0 x 4</td> </tr>\r\n  <tr> <td>USB 3.1:</td> <td>USB 3.1 C Tipi x 1</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>Yok</td> </tr>\r\n  <tr> <td>Fan:</td> <td>120mm x 5</td> </tr>\r\n</table>\r\n            '),
(43, 'Kasa', 'Gigabyte', 'PSU Yok', 'GIGABYTE C200 GLASS RGB Tempered Glass USB 3.0 Mid Tower Kasa', 1700, 10, 'images/urunler/kasa-gigabyte-c200.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kasa Tipi:</td> <td>ATX Mid Tower</td> </tr>\r\n  <tr> <td>PSU:</td> <td>Yok</td> </tr>\r\n  <tr> <td>PSU Konumu:</td> <td>Aşağıda</td> </tr>\r\n  <tr> <td>Internal 3.5\":</td> <td>2</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>2</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 1</td> </tr>\r\n  <tr> <td>USB 3.0:</td> <td>USB 3.0 x 2</td> </tr>\r\n  <tr> <td>USB 3.1:</td> <td>USB 3.1 x 1</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x 1</td> </tr>\r\n  <tr> <td>Fan:</td> <td>120mm x 1</td> </tr>\r\n</table>\r\n            '),
(44, 'Kasa', 'Msi', 'PSU Yok', 'MSI MAG SHIELD M300 Tempered Glass USB 3.2 Mid Tower Kasa', 800, 10, 'images/urunler/kasa-msi-m300.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kasa Tipi:</td> <td>MicroATX, Mini-ITX</td> </tr>\r\n  <tr> <td>PSU:</td> <td>Yok</td> </tr>\r\n  <tr> <td>PSU Konumu:</td> <td>Aşağıda</td> </tr>\r\n  <tr> <td>Internal 3.5\":</td> <td>2</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>2</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>USB 2.0:</td> <td>USB 2.0 x 2</td> </tr>\r\n  <tr> <td>USB 3.0:</td> <td>Yok</td> </tr>\r\n  <tr> <td>USB 3.1:</td> <td>Yok</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x 1</td> </tr>\r\n  <tr> <td>Fan:</td> <td>Yok</td> </tr>\r\n</table>\r\n            '),
(45, 'Kasa', 'Msi', 'PSU Yok', 'MSI MPG VELOX 100P AIRFLOW A-RGB USB-C 2xUSB 3.2 Tempered Glass Siyah ATX Mid Tower Kasa', 3500, 10, 'images/urunler/kasa-msi-velox.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kasa Tipi:</td> <td>ATX Mid Tower</td> </tr>\r\n  <tr> <td>PSU:</td> <td>Yok</td> </tr>\r\n  <tr> <td>PSU Konumu:</td> <td>Aşağıda</td> </tr>\r\n  <tr> <td>Internal 3.5\":</td> <td>2</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>2</td> </tr>\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>USB 2.0:</td> <td>Yok</td> </tr>\r\n  <tr> <td>USB 3.0:</td> <td>Yok</td> </tr>\r\n  <tr> <td>USB 3.1:</td> <td>Yok</td> </tr>\r\n  <tr> <td>USB 3.2:</td> <td>USB 3.2 x 2</td> </tr>\r\n  <tr> <td>Fan:</td> <td>120mm x 1</td> </tr>\r\n</table>\r\n            '),
(46, 'Güç Kaynağı', 'Asus', '550W', 'ASUS TUF GAMING 550B 550W 80+ Bronze 135mm Fanlı PSU', 2100, 10, 'images/urunler/psu-asus-550w.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Güç:</td> <td>550W</td> </tr>\r\n  <tr> <td>Güç Verimliliği:</td> <td>80 PLUS BRONZE</td> </tr>\r\n  <tr> <td>Modüler:</td> <td>Yok</td> </tr>\r\n  <tr> <td>PSU Tip:</td> <td>ATX12V</td> </tr>\r\n<!--  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ana Konnektör:</td> <td>24Pin</td> </tr>\r\n  <tr> <td>PCI-E Bağlantısı:</td> <td>6+2-Pin x 2</td> </tr>\r\n  <tr> <td>Sata Bağlantısı:</td> <td>5</td> </tr>\r\n  <tr> <td>Fan:</td> <td>1</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(47, 'Güç Kaynağı', 'Asus', '750W', 'ASUS TUF GAMING 750B 750W 80+ Bronze 135mm Fanlı PSU', 2600, 10, 'images/urunler/psu-asus-750w.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Güç:</td> <td>750W</td> </tr>\r\n  <tr> <td>Güç Verimliliği:</td> <td>80 PLUS BRONZE</td> </tr>\r\n  <tr> <td>Modüler:</td> <td>Yok</td> </tr>\r\n  <tr> <td>PSU Tip:</td> <td>ATX12V</td> </tr>\r\n<!--  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ana Konnektör:</td> <td>24Pin</td> </tr>\r\n  <tr> <td>PCI-E Bağlantısı:</td> <td>6+2-Pin x 4</td> </tr>\r\n  <tr> <td>Sata Bağlantısı:</td> <td>8</td> </tr>\r\n  <tr> <td>Fan:</td> <td>1</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(48, 'Güç Kaynağı', 'Asus', '1000W', 'ASUS ROG STRIX 1000W 80+ Gold Full Modüler PSU', 4600, 10, 'images/urunler/psu-asus-1000w.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Güç:</td> <td>1000W</td> </tr>\r\n  <tr> <td>Güç Verimliliği:</td> <td>80 PLUS GOLD</td> </tr>\r\n  <tr> <td>Modüler:</td> <td>Full Modüler</td> </tr>\r\n  <tr> <td>PSU Tip:</td> <td>ATX12V</td> </tr>\r\n<!--  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ana Konnektör:</td> <td>24Pin</td> </tr>\r\n  <tr> <td>PCI-E Bağlantısı:</td> <td>6+2-Pin x 6</td> </tr>\r\n  <tr> <td>Sata Bağlantısı:</td> <td>8</td> </tr>\r\n  <tr> <td>Fan:</td> <td>1</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(49, 'Güç Kaynağı', 'Corsair', '750W', 'CORSAIR RM750 750W 80+ Gold Full Modüler 135mm Fanlı Beyaz ATX PSU', 3000, 10, 'images/urunler/psu-corsair-750w.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Güç:</td> <td>750W </td> </tr>\r\n  <tr> <td>Güç Verimliliği:</td> <td>80 PLUS GOLD</td> </tr>\r\n  <tr> <td>Modüler:</td> <td>Full Modüler</td> </tr>\r\n  <tr> <td>PSU Tip:</td> <td>ATX12V</td> </tr>\r\n<!--  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ana Konnektör:</td> <td>20+4Pin</td> </tr>\r\n  <tr> <td>PCI-E Bağlantısı:</td> <td>6+2-Pin x 4</td> </tr>\r\n  <tr> <td>Sata Bağlantısı:</td> <td>6</td> </tr>\r\n  <tr> <td>Fan:</td> <td>1</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(50, 'Güç Kaynağı', 'Corsair', '850W', 'CORSAIR RM850 850W 80+ Gold Full Modüler 135mm Fanlı ATX PSU', 2000, 10, 'images/urunler/psu-corsair-850w.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Güç:</td> <td>850W</td> </tr>\r\n  <tr> <td>Güç Verimliliği:</td> <td>80 PLUS GOLD</td> </tr>\r\n  <tr> <td>Modüler:</td> <td>Full Modüler</td> </tr>\r\n  <tr> <td>PSU Tip:</td> <td>ATX</td> </tr>\r\n<!--  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ana Konnektör:</td> <td>20+4Pin</td> </tr>\r\n  <tr> <td>PCI-E Bağlantısı:</td> <td>6+2-Pin x 4</td> </tr>\r\n  <tr> <td>Sata Bağlantısı:</td> <td>10</td> </tr>\r\n  <tr> <td>Fan:</td> <td>1</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(51, 'Güç Kaynağı', 'Corsair', '1000W', 'CORSAIR HX1000 1000W 80+ Platinum Full Modüler 135mm Fanlı PSU', 5100, 10, 'images/urunler/psu-corsair-1000w.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Güç:</td> <td>1000W</td> </tr>\r\n  <tr> <td>Güç Verimliliği:</td> <td>80 PLUS PLATINUM</td> </tr>\r\n  <tr> <td>Modüler:</td> <td>Full Modüler</td> </tr>\r\n  <tr> <td>PSU Tip:</td> <td>ATX</td> </tr>\r\n<!--  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ana Konnektör:</td> <td>20+4Pin</td> </tr>\r\n  <tr> <td>PCI-E Bağlantısı:</td> <td>6+2-Pin x 8</td> </tr>\r\n  <tr> <td>Sata Bağlantısı:</td> <td>16</td> </tr>\r\n  <tr> <td>Fan:</td> <td>1</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(52, 'Güç Kaynağı', 'Gigabyte', '650W', 'GIGABYTE P650B 650W 80+ Bronze 120mm Fanlı PSU', 1300, 10, 'images/urunler/psu-gigabyte-650w.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Güç:</td> <td>650W</td> </tr>\r\n  <tr> <td>Güç Verimliliği:</td> <td>80 PLUS BRONZE</td> </tr>\r\n  <tr> <td>Modüler:</td> <td>Yok</td> </tr>\r\n  <tr> <td>PSU Tip:</td> <td>ATX</td> </tr>\r\n<!--  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ana Konnektör:</td> <td>20+4Pin</td> </tr>\r\n  <tr> <td>PCI-E Bağlantısı:</td> <td>6+2-Pin x 4</td> </tr>\r\n  <tr> <td>Sata Bağlantısı:</td> <td>6</td> </tr>\r\n  <tr> <td>Fan:</td> <td>1</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(53, 'Güç Kaynağı', 'Gigabyte', '850W', 'GIGABYTE AORUS AP850GM 850W 80+ Gold Full Modüler 135mm Fanlı PSU', 3000, 10, 'images/urunler/psu-gigabyte-850w.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Güç:</td> <td>850W</td> </tr>\r\n  <tr> <td>Güç Verimliliği:</td> <td>80 PLUS GOLD</td> </tr>\r\n  <tr> <td>Modüler:</td> <td>Full Modüler</td> </tr>\r\n  <tr> <td>PSU Tip:</td> <td>ATX</td> </tr>\r\n<!--  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ana Konnektör:</td> <td>20+4Pin</td> </tr>\r\n  <tr> <td>PCI-E Bağlantısı:</td> <td>6+2-Pin x 6</td> </tr>\r\n  <tr> <td>Sata Bağlantısı:</td> <td>6</td> </tr>\r\n  <tr> <td>Fan:</td> <td>1</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(54, 'Güç Kaynağı', 'Msi', '650W', 'MSI MPG A650GF 650W 80+ Gold Full Modüler 140mm Fanlı PSU', 2000, 10, 'images/urunler/psu-msi-650w.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Güç:</td> <td>650W</td> </tr>\r\n  <tr> <td>Güç Verimliliği:</td> <td>80 PLUS GOLD</td> </tr>\r\n  <tr> <td>Modüler:</td> <td>Full Modüler</td> </tr>\r\n  <tr> <td>PSU Tip:</td> <td>ATX</td> </tr>\r\n<!--  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ana Konnektör:</td> <td>20+4Pin</td> </tr>\r\n  <tr> <td>PCI-E Bağlantısı:</td> <td>6+2-Pin x 4</td> </tr>\r\n  <tr> <td>Sata Bağlantısı:</td> <td>7</td> </tr>\r\n  <tr> <td>Fan:</td> <td>1</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(55, 'Güç Kaynağı', 'Msi', '850W', 'MSI MPG A850GF 850W 80+ Gold Full Modüler 140mm Fanlı PSU', 3000, 10, 'images/urunler/psu-msi-850w.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Güç:</td> <td>850W</td> </tr>\r\n  <tr> <td>Güç Verimliliği:</td> <td>80 PLUS GOLD</td> </tr>\r\n  <tr> <td>Modüler:</td> <td>Full Modüler</td> </tr>\r\n  <tr> <td>PSU Tip:</td> <td>SFX</td> </tr>\r\n<!--  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ana Konnektör:</td> <td>24Pin</td> </tr>\r\n  <tr> <td>PCI-E Bağlantısı:</td> <td>8-Pin x 4</td> </tr>\r\n  <tr> <td>Sata Bağlantısı:</td> <td>4</td> </tr>\r\n  <tr> <td>Fan:</td> <td>1</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(56, 'Güç Kaynağı', 'Msi', '1000W', 'MSI MPG A1000G 1000W 80+ Gold Full Modüler 135mm Fanlı PSU', 3700, 10, 'images/urunler/psu-msi-1000w.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Güç:</td> <td>1000W</td> </tr>\r\n  <tr> <td>Güç Verimliliği:</td> <td>80 PLUS GOLD</td> </tr>\r\n  <tr> <td>Modüler:</td> <td>Full Modüler</td> </tr>\r\n  <tr> <td>PSU Tip:</td> <td>ATX</td> </tr>\r\n<!--  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Ana Konnektör:</td> <td>24Pin</td> </tr>\r\n  <tr> <td>PCI-E Bağlantısı:</td> <td>6+2-Pin x 7</td> </tr>\r\n  <tr> <td>Sata Bağlantısı:</td> <td>12</td> </tr>\r\n  <tr> <td>Fan:</td> <td>1</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(57, 'Depolama', 'Wd', 'SATA SSD', 'WD 480GB Green SATA 3.0 2.5\" SSD (545MB Okuma / 465MB Yazma)', 900, 10, 'images/urunler/depolama-wd-satassd-480gb.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kapasite:</td> <td>480GB</td> </tr>\r\n  <tr> <td>SSD Tipi:</td> <td>2.5\"</td> </tr>\r\n  <tr> <td>Bağlantı Arayüz:</td> <td>SATA 6.0Gb/s</td> </tr>\r\n<!--  <tr> <td>:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Okuma/Yazma Hızı:</td> <td>545/445MBps</td> </tr>\r\n  <tr> <td>Max 4K Okuma:</td> <td>80.000 IOPS</td> </tr>\r\n  <tr> <td>Max 4k Yazma:</td> <td>88.000 IOPS</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(58, 'Depolama', 'Wd', 'SATA SSD', 'WD 250GB Blue SATA 3.0 2.5 SSD (550MB Okuma/525MB Yazma)', 1200, 10, 'images/urunler/depolama-wd-satassd-250gb.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kapasite:</td> <td>250GB</td> </tr>\r\n  <tr> <td>SSD Tipi:</td> <td>2.5\"</td> </tr>\r\n  <tr> <td>Bağlantı Arayüz:</td> <td>SATA 6.0Gb/s</td> </tr>\r\n<!--  <tr> <td>:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Okuma/Yazma Hızı:</td> <td>550/525MBps</td> </tr>\r\n  <tr> <td>Max 4K Okuma:</td> <td>95.000 IOPS</td> </tr>\r\n  <tr> <td>Max 4k Yazma:</td> <td>80.000 IOPS</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            ');
INSERT INTO `urunler` (`id`, `kategori`, `marka`, `model`, `baslik`, `fiyat`, `stok`, `gorsel`, `ozellikler`) VALUES
(59, 'Depolama', 'Wd', 'M.2 SSD', 'WD BLACK 2TB SN770 NVMe M.2 2280 SSD (5150MB Okuma / 4850MB Yazma)', 5200, 10, 'images/urunler/depolama-wd-m2ssd-2tb.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kapasite:</td> <td>2TB</td> </tr>\r\n  <tr> <td>SSD Tipi:</td> <td>M.2 2280</td> </tr>\r\n  <tr> <td>Bağlantı Arayüz:</td> <td>PCI-Express 4.0 x4</td> </tr>\r\n<!--  <tr> <td>:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Max Okuma/Yazma Hızı:</td> <td>5150/4850 MBps</td> </tr>\r\n  <tr> <td>Max 4K Okuma:</td> <td>750.000 IOPS</td> </tr>\r\n  <tr> <td>Max 4k Yazma:</td> <td>800.000 IOPS\r\n</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(60, 'Depolama', 'Msi', 'M.2 SSD', 'MSI 1TB SPATIUM M450 Gen4x4 M.2 2280 SSD (3600MB Okuma / 3000MB Yazma)', 2300, 10, 'images/urunler/depolama-msi-m2ssd-1tb.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kapasite:</td> <td>1TB</td> </tr>\r\n  <tr> <td>SSD Tipi:</td> <td>M.2 2280</td> </tr>\r\n  <tr> <td>Bağlantı Arayüz:</td> <td>PCI-Express 4.0 x4</td> </tr>\r\n<!--  <tr> <td>:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Okuma/Yazma Hızı:</td> <td>3600/3000 MBps</td> </tr>\r\n  <tr> <td>Max 4K Okuma:</td> <td>420.000 IOPS</td> </tr>\r\n  <tr> <td>Max 4k Yazma:</td> <td>550.000 IOPS</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(61, 'Depolama', 'Msi', 'M.2 SSD', 'MSI 1TB SPATIUM M480 PCIe 4.0 NVMe M.2 SSD (7000MB Okuma / 5500MB Yazma)', 3000, 10, 'images/urunler/depolama-msi-m2ssd-1tb-s.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kapasite:</td> <td>1TB</td> </tr>\r\n  <tr> <td>SSD Tipi:</td> <td>M.2 2280</td> </tr>\r\n  <tr> <td>Bağlantı Arayüz:</td> <td>PCI-Express 4.0 x4</td> </tr>\r\n<!--  <tr> <td>:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Okuma/Yazma Hızı:</td> <td>7000/5500 MBps</td> </tr>\r\n  <tr> <td>Max 4K Okuma:</td> <td>350.000 IOPS</td> </tr>\r\n  <tr> <td>Max 4k Yazma:</td> <td>700.000 IOPS</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(62, 'Depolama', 'Asus', 'M.2 SSD', 'ASUS ROG STRIX 1TB SQ7 Gen4x4 M.2 2280 NVMe SSD (7000MB Okuma / 6000MB Yazma)', 3900, 10, 'images/urunler/depolama-asus-m2ssd-1tb.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kapasite:</td> <td>1TB</td> </tr>\r\n  <tr> <td>SSD Tipi:</td> <td>M.2 2280</td> </tr>\r\n  <tr> <td>Bağlantı Arayüz:</td> <td>PCI-Express 4.0 x4</td> </tr>\r\n<!--  <tr> <td>:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Okuma/Yazma Hızı:</td> <td>7000/6000 MBps</td> </tr>\r\n  <tr> <td>Max 4K Okuma:</td> <td>530.000 IOPS</td> </tr>\r\n  <tr> <td>Max 4k Yazma:</td> <td>550.000 IOPS</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(63, 'Depolama', 'Corsair', 'M.2 SSD', 'CORSAIR 480GB Force MP510 NVMe M.2 SSD (3480MB Okuma / 2000MB Yazma)', 2100, 10, 'images/urunler/depolama-corsair-m2ssd-480gb.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kapasite:</td> <td>480GB</td> </tr>\r\n  <tr> <td>SSD Tipi:</td> <td>M.2</td> </tr>\r\n  <tr> <td>Bağlantı Arayüz:</td> <td>PCI-Express 3.0 x4</td> </tr>\r\n<!--  <tr> <td>:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Okuma/Yazma Hızı:</td> <td>3480/2000 MBps</td> </tr>\r\n  <tr> <td>Max 4K Okuma:</td> <td>120.000 IOPS</td> </tr>\r\n  <tr> <td>Max 4k Yazma:</td> <td>490.000 IOPS</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            '),
(64, 'Depolama', 'Corsair', 'M.2 SSD', 'CORSAIR 1TB Force MP600 CORE NVMe PCIe Gen 4 M.2 SSD (4700MB Okuma / 1950MB Yazma)', 3100, 10, 'images/urunler/depolama-corsair-m2ssd-1tb.jpg', '\r\n<table class=\"urun-table\">\r\n  <tr> <td>Kapasite:</td> <td>1TB</td> </tr>\r\n  <tr> <td>SSD Tipi:</td> <td>M.2 2280</td> </tr>\r\n  <tr> <td>Bağlantı Arayüz:</td> <td>PCI-Express 4.0 x4</td> </tr>\r\n<!--  <tr> <td>:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Internal 2.5\":</td> <td>xxx</td> </tr>-->\r\n</table>\r\n\r\n  </div><div class=\"col-6 pe-4\">\r\n\r\n<table class=\"urun-table\">\r\n  <tr> <td>Okuma/Yazma Hızı:</td> <td>4700/1950 MBps</td> </tr>\r\n  <tr> <td>Max 4K Okuma:</td> <td>480.000 IOPS</td> </tr>\r\n  <tr> <td>Max 4k Yazma:</td> <td>200.000 IOPS</td> </tr>\r\n<!--  <tr> <td>Fan:</td> <td>xxx</td> </tr>\r\n  <tr> <td>Fan:</td> <td>xxx</td> </tr>-->\r\n</table>\r\n            ');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `musteri`
--
ALTER TABLE `musteri`
  ADD PRIMARY KEY (`id`);

--
-- Tablo için indeksler `urunler`
--
ALTER TABLE `urunler`
  ADD PRIMARY KEY (`id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `musteri`
--
ALTER TABLE `musteri`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- Tablo için AUTO_INCREMENT değeri `urunler`
--
ALTER TABLE `urunler`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=70;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
